#server:
#  port: 8001
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          lowerCaseServiceId: true
#          enabled: true
#
#routers:
#  ignore:
#    urls:
#      - /actuator/**
#      - /auth/**
#      - /favicon.ico
#feign:
#  sentinel:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: true